### ISSUE TITLE
cbake is listed twice in the project list

### ISSUE THREAD

**Issue by jjkavalam** [manparvesh/manparvesh.github.io#32]

**Comment by manparvesh** [comment]
@jjkavalam no, you might be looking in the news section. That contains recent projects, blog posts, and publications. There are entries for `cbake` in both blog posts and projects, that's why you saw that.

**Comment by jjkavalam** [comment]
Sorry, the report wasn't descriptive enough. 
The listing on https://manparvesh.com/projects/ is ok, but the one on the home page https://manparvesh.com/ is having the problem.

**Comment by manparvesh** [comment]
@jjkavalam yes, that is the news section.
If you see the URLs, both the entries are different
